// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdIHRdsN_CmiibGv59PGgqXSNM0CossA',
    appId: '1:745665393864:web:4d4fbadebb71366675a1fd',
    messagingSenderId: '745665393864',
    projectId: 'smart-learn-app-b3843',
    authDomain: 'smart-learn-app-b3843.firebaseapp.com',
    storageBucket: 'smart-learn-app-b3843.firebasestorage.app',
    measurementId: 'G-RR12T1L2T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh77hNjclfLMTt5iXcC96Xopju9Am_Jgw',
    appId: '1:745665393864:android:94ab56a65751ecd775a1fd',
    messagingSenderId: '745665393864',
    projectId: 'smart-learn-app-b3843',
    storageBucket: 'smart-learn-app-b3843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJhVeVVWC4pR3M_C2-60sxq0AF9WJakE',
    appId: '1:745665393864:ios:d2b0d7e943668c8e75a1fd',
    messagingSenderId: '745665393864',
    projectId: 'smart-learn-app-b3843',
    storageBucket: 'smart-learn-app-b3843.firebasestorage.app',
    iosBundleId: 'com.example.smartLearnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJhVeVVWC4pR3M_C2-60sxq0AF9WJakE',
    appId: '1:745665393864:ios:d2b0d7e943668c8e75a1fd',
    messagingSenderId: '745665393864',
    projectId: 'smart-learn-app-b3843',
    storageBucket: 'smart-learn-app-b3843.firebasestorage.app',
    iosBundleId: 'com.example.smartLearnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcdIHRdsN_CmiibGv59PGgqXSNM0CossA',
    appId: '1:745665393864:web:e4cbc5b78a66b13675a1fd',
    messagingSenderId: '745665393864',
    projectId: 'smart-learn-app-b3843',
    authDomain: 'smart-learn-app-b3843.firebaseapp.com',
    storageBucket: 'smart-learn-app-b3843.firebasestorage.app',
    measurementId: 'G-90PL5206YE',
  );

}